# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: home-pc-agent

before:
  hooks:
    - go mod tidy

builds:
  - id: home-pc-agent
    main: ./cmd/home-pc-agent
    binary: home-pc-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: home-pc-agent
    ids:
      - home-pc-agent
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore\\(deps\\):"

release:
  github:
    owner: tarik02
    name: home-pc-agent
  prerelease: auto
  mode: append
