syntax = "proto3";

package fancontrol.v1;

option go_package = "github.com/tarik02/home-pc-agent/internal/plugins/fancontrol";

message RequestInit {
  string method = 1;
  int32 call_type = 3;
}

message PayloadInfo {
  int32 size = 1;
  bool in_same_packet = 2;
}

message Trailers {
  int32 status_code = 2;
  string status_detail = 3;
}

message TransportMessage {
  RequestInit request_init = 1;
  bytes request_control = 2;
  PayloadInfo payload_info = 3;
  Trailers trailers = 5;
}

message ListAvailableConfigsReply {
  repeated string configs = 1;
  string current_config = 2;
  string config_folder = 3;
}

message LoadConfigRequest {
  string config_name = 1;
}

enum CommandStatus {
  COMMAND_STATUS_UNSPECIFIED = 0;
  COMMAND_STATUS_OK = 1;
  COMMAND_STATUS_EXIT = 2;
  COMMAND_STATUS_REJECTED = 3;
  COMMAND_STATUS_UNSUPPORTED = 4;
}

message CommandReply {
  CommandStatus status = 1;
  string user = 2;
}
