// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: fancontrol.proto

package fancontrol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_OK          CommandStatus = 1
	CommandStatus_COMMAND_STATUS_EXIT        CommandStatus = 2
	CommandStatus_COMMAND_STATUS_REJECTED    CommandStatus = 3
	CommandStatus_COMMAND_STATUS_UNSUPPORTED CommandStatus = 4
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_OK",
		2: "COMMAND_STATUS_EXIT",
		3: "COMMAND_STATUS_REJECTED",
		4: "COMMAND_STATUS_UNSUPPORTED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_OK":          1,
		"COMMAND_STATUS_EXIT":        2,
		"COMMAND_STATUS_REJECTED":    3,
		"COMMAND_STATUS_UNSUPPORTED": 4,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fancontrol_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_fancontrol_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{0}
}

type RequestInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	CallType      int32                  `protobuf:"varint,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInit) Reset() {
	*x = RequestInit{}
	mi := &file_fancontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInit) ProtoMessage() {}

func (x *RequestInit) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInit.ProtoReflect.Descriptor instead.
func (*RequestInit) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{0}
}

func (x *RequestInit) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestInit) GetCallType() int32 {
	if x != nil {
		return x.CallType
	}
	return 0
}

type PayloadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	InSamePacket  bool                   `protobuf:"varint,2,opt,name=in_same_packet,json=inSamePacket,proto3" json:"in_same_packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadInfo) Reset() {
	*x = PayloadInfo{}
	mi := &file_fancontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadInfo) ProtoMessage() {}

func (x *PayloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadInfo.ProtoReflect.Descriptor instead.
func (*PayloadInfo) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PayloadInfo) GetInSamePacket() bool {
	if x != nil {
		return x.InSamePacket
	}
	return false
}

type Trailers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusDetail  string                 `protobuf:"bytes,3,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailers) Reset() {
	*x = Trailers{}
	mi := &file_fancontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailers) ProtoMessage() {}

func (x *Trailers) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailers.ProtoReflect.Descriptor instead.
func (*Trailers) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{2}
}

func (x *Trailers) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Trailers) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

type TransportMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestInit    *RequestInit           `protobuf:"bytes,1,opt,name=request_init,json=requestInit,proto3" json:"request_init,omitempty"`
	RequestControl []byte                 `protobuf:"bytes,2,opt,name=request_control,json=requestControl,proto3" json:"request_control,omitempty"`
	PayloadInfo    *PayloadInfo           `protobuf:"bytes,3,opt,name=payload_info,json=payloadInfo,proto3" json:"payload_info,omitempty"`
	Trailers       *Trailers              `protobuf:"bytes,5,opt,name=trailers,proto3" json:"trailers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransportMessage) Reset() {
	*x = TransportMessage{}
	mi := &file_fancontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportMessage) ProtoMessage() {}

func (x *TransportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportMessage.ProtoReflect.Descriptor instead.
func (*TransportMessage) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{3}
}

func (x *TransportMessage) GetRequestInit() *RequestInit {
	if x != nil {
		return x.RequestInit
	}
	return nil
}

func (x *TransportMessage) GetRequestControl() []byte {
	if x != nil {
		return x.RequestControl
	}
	return nil
}

func (x *TransportMessage) GetPayloadInfo() *PayloadInfo {
	if x != nil {
		return x.PayloadInfo
	}
	return nil
}

func (x *TransportMessage) GetTrailers() *Trailers {
	if x != nil {
		return x.Trailers
	}
	return nil
}

type ListAvailableConfigsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []string               `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	CurrentConfig string                 `protobuf:"bytes,2,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"`
	ConfigFolder  string                 `protobuf:"bytes,3,opt,name=config_folder,json=configFolder,proto3" json:"config_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableConfigsReply) Reset() {
	*x = ListAvailableConfigsReply{}
	mi := &file_fancontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableConfigsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableConfigsReply) ProtoMessage() {}

func (x *ListAvailableConfigsReply) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableConfigsReply.ProtoReflect.Descriptor instead.
func (*ListAvailableConfigsReply) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{4}
}

func (x *ListAvailableConfigsReply) GetConfigs() []string {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListAvailableConfigsReply) GetCurrentConfig() string {
	if x != nil {
		return x.CurrentConfig
	}
	return ""
}

func (x *ListAvailableConfigsReply) GetConfigFolder() string {
	if x != nil {
		return x.ConfigFolder
	}
	return ""
}

type LoadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadConfigRequest) Reset() {
	*x = LoadConfigRequest{}
	mi := &file_fancontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadConfigRequest) ProtoMessage() {}

func (x *LoadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadConfigRequest.ProtoReflect.Descriptor instead.
func (*LoadConfigRequest) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{5}
}

func (x *LoadConfigRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

type CommandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CommandStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=fancontrol.v1.CommandStatus" json:"status,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReply) Reset() {
	*x = CommandReply{}
	mi := &file_fancontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReply) ProtoMessage() {}

func (x *CommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_fancontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReply.ProtoReflect.Descriptor instead.
func (*CommandReply) Descriptor() ([]byte, []int) {
	return file_fancontrol_proto_rawDescGZIP(), []int{6}
}

func (x *CommandReply) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandReply) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_fancontrol_proto protoreflect.FileDescriptor

var file_fancontrol_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x61, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x66, 0x61, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x22, 0x42, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x6c,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6e, 0x5f, 0x73,
	0x61, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x6e, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x50,
	0x0a, 0x08, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0xee, 0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x61,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x69, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x3d, 0x0a,
	0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x61, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x66, 0x61, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x73, 0x52, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72,
	0x73, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x58, 0x0a, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x66, 0x61,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x2a, 0x9c, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41,
	0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4d, 0x4d, 0x41,
	0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x45, 0x58, 0x49, 0x54, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4d, 0x4d, 0x41,
	0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54,
	0x45, 0x44, 0x10, 0x04, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x6b, 0x30, 0x32, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2d,
	0x70, 0x63, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x66, 0x61, 0x6e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fancontrol_proto_rawDescOnce sync.Once
	file_fancontrol_proto_rawDescData = file_fancontrol_proto_rawDesc
)

func file_fancontrol_proto_rawDescGZIP() []byte {
	file_fancontrol_proto_rawDescOnce.Do(func() {
		file_fancontrol_proto_rawDescData = protoimpl.X.CompressGZIP(file_fancontrol_proto_rawDescData)
	})
	return file_fancontrol_proto_rawDescData
}

var file_fancontrol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fancontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fancontrol_proto_goTypes = []any{
	(CommandStatus)(0),                // 0: fancontrol.v1.CommandStatus
	(*RequestInit)(nil),               // 1: fancontrol.v1.RequestInit
	(*PayloadInfo)(nil),               // 2: fancontrol.v1.PayloadInfo
	(*Trailers)(nil),                  // 3: fancontrol.v1.Trailers
	(*TransportMessage)(nil),          // 4: fancontrol.v1.TransportMessage
	(*ListAvailableConfigsReply)(nil), // 5: fancontrol.v1.ListAvailableConfigsReply
	(*LoadConfigRequest)(nil),         // 6: fancontrol.v1.LoadConfigRequest
	(*CommandReply)(nil),              // 7: fancontrol.v1.CommandReply
}
var file_fancontrol_proto_depIdxs = []int32{
	1, // 0: fancontrol.v1.TransportMessage.request_init:type_name -> fancontrol.v1.RequestInit
	2, // 1: fancontrol.v1.TransportMessage.payload_info:type_name -> fancontrol.v1.PayloadInfo
	3, // 2: fancontrol.v1.TransportMessage.trailers:type_name -> fancontrol.v1.Trailers
	0, // 3: fancontrol.v1.CommandReply.status:type_name -> fancontrol.v1.CommandStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_fancontrol_proto_init() }
func file_fancontrol_proto_init() {
	if File_fancontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fancontrol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fancontrol_proto_goTypes,
		DependencyIndexes: file_fancontrol_proto_depIdxs,
		EnumInfos:         file_fancontrol_proto_enumTypes,
		MessageInfos:      file_fancontrol_proto_msgTypes,
	}.Build()
	File_fancontrol_proto = out.File
	file_fancontrol_proto_rawDesc = nil
	file_fancontrol_proto_goTypes = nil
	file_fancontrol_proto_depIdxs = nil
}
